apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ncx-ide.fullname" . }}-configjs
  labels:
    {{- include "ncx-ide.labels" . | nindent 4 }}
data:
  config.js: |
    function config () {
      return { 
        buildServerAddress: "http://ncxserverless.com/api",
      };
    }
    