name: NCX IDE Chart
on:
  push:
    paths:
      - 'charts/ncx-ide/**'
      - .github/workflows/reusable-helm.yaml
      - .github/workflows/ncx-ide-chart.yaml
    branches:
      - master
  pull_request:
    paths:
      - 'charts/ncx-ide/**'
      - .github/workflows/reusable-helm.yaml
      - .github/workflows/ncx-ide-chart.yaml

jobs:
  helm:
    uses: briand787b/ncx-infra/.github/workflows/reusable-helm.yaml@master
    with:
      namespace: store
      cluster: ncx-auto-gke
      cluster-zone: us-east1
    secrets:
      gcloud-token: ${{ secrets.GCLOUD_TOKEN }}
    