name: NCX Gateway-Store Chart
on:
  push:
    paths:
      - 'charts/ncx-gateway-store/**'
      - .github/workflows/reusable-helm.yaml
      - .github/workflows/ncx-gateway-store-chart.yaml
    branches:
      - master
  pull_request:
    paths:
      - 'charts/ncx-gateway-store/**'
      - .github/workflows/reusable-helm.yaml
      - .github/workflows/ncx-gateway-store-chart.yaml

jobs:
  helm:
    uses: briand787b/ncx-infra/.github/workflows/reusable-helm.yaml@master
    with:
      chart-path: 'charts/ncx-gateway-store'
      release: ncx-gateway-store
      namespace: store
      cluster: ncx-auto-gke
      cluster-zone: us-east1
    secrets:
      gcloud-token: ${{ secrets.GCLOUD_TOKEN }}
    